directive @auth on FIELD_DEFINITION

type Post {
  id: ID!
  title: String!
  content: String!
  allowComments: Boolean!
  comments: [Comment!]!
}

type Comment {
  id: ID!
  postId: ID!
  parentId: ID
  content: String!
  replies: [Comment!]
}

type User {
  id: ID!
  login: String!
}

type Query {
    posts: [Post!]!
    post(id: ID!): Post
}

type Mutation {
    register(login: String!, password: String!): User!
    createPost(title: String!, content: String!): Post! @auth
    addComment(postId: ID!, parentId: ID, content: String!): Comment! @auth
}

type Subscription {
    newComment(postId: ID!): Comment!
}
