package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"strconv"

	"github.com/haranton/go-graphql-blog/graph/model"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *model.Comment, limit int32, offset int32) ([]*model.Comment, error) {
	if obj == nil || obj.ID == "" || obj.PostID == "" {
		return []*model.Comment{}, nil
	}
	return r.Service.SrvComm.GetReplies(ctx, obj.PostID, obj.ID, int(limit), int(offset))
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, login string, password string) (*model.User, error) {
	createdUser, err := r.Service.SrvAuth.RegisterUser(ctx, login, password)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:    strconv.Itoa(createdUser.ID),
		Login: createdUser.Login,
	}, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string, content string) (*model.Post, error) {
	post, err := r.Service.SrvPost.CreatePost(ctx, title, content)
	if err != nil {
		return nil, err
	}

	return post, nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, postID string, parentID *string, content string) (*model.Comment, error) {
	posts, err := r.Service.SrvComm.AddComment(ctx, postID, parentID, content)
	if err != nil {
		fmt.Println("Error:", err)
		return nil, err
	}

	return posts, nil
}

// DisallowComments is the resolver for the disallowComments field.
func (r *mutationResolver) DisallowComments(ctx context.Context, postID string) (bool, error) {
	return r.Service.SrvPost.DisallowComments(ctx, postID)
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, limit int32, offset int32) ([]*model.Comment, error) {
	if obj == nil || obj.ID == "" {
		return []*model.Comment{}, nil
	}
	return r.Service.SrvComm.GetComments(ctx, obj.ID, int(limit), int(offset))
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	posts, err := r.Service.SrvPost.Posts(ctx)
	if err != nil {
		fmt.Println("Error:", err)
		return nil, err
	}

	return posts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	postWithComments, err := r.Service.SrvPost.PostWithComments(ctx, id)
	if err != nil {
		fmt.Println("Error:", err)
		return nil, err
	}

	return postWithComments, nil
}

// NewComment is the resolver for the newComment field.
func (r *subscriptionResolver) NewComment(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	panic(fmt.Errorf("not implemented: NewComment - newComment"))
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
